version: '3.1'

services:
  app:
    image: app:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    env_file:
      - ./.env
  postgres:
    image: postgres:12
    restart: always
    expose:
      - '5432'
    env_file:
      - ./.env
    volumes:
      - postgresql:/var/lib/postgresql
volumes:
  postgresql:

