"""Adding agent column at Events

Revision ID: 0b39a6605996
Revises: 00d151620ef7
Create Date: 2020-09-30 23:44:49.016364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b39a6605996'
down_revision = '00d151620ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'agent')
    # ### end Alembic commands ###
