"""Changind Sites.site to Sites.url

Revision ID: 3ef119743b66
Revises: f5fb42e02e69
Create Date: 2020-10-02 17:04:52.571838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef119743b66'
down_revision = 'f5fb42e02e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('url', sa.String(length=50), nullable=True))
    op.drop_constraint('sites_site_key', 'sites', type_='unique')
    op.create_unique_constraint(None, 'sites', ['url'])
    op.drop_column('sites', 'site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('site', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sites', type_='unique')
    op.create_unique_constraint('sites_site_key', 'sites', ['site'])
    op.drop_column('sites', 'url')
    # ### end Alembic commands ###
