"""Adding new tables

Revision ID: 6ac51b7ebd2b
Revises: 
Create Date: 2020-09-29 16:30:24.795762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac51b7ebd2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=39), nullable=True),
    sa.Column('cid', sa.String(length=10), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('doc_title', sa.Text(), nullable=True),
    sa.Column('doc_uri', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=39), nullable=True),
    sa.Column('cid', sa.String(length=10), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('doc_title', sa.Text(), nullable=True),
    sa.Column('doc_uri', sa.Text(), nullable=True),
    sa.Column('doc_enc', sa.String(length=25), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('_referrer', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=25), nullable=True),
    sa.Column('browser', sa.String(length=25), nullable=True),
    sa.Column('version', sa.String(length=25), nullable=True),
    sa.Column('screen_res', sa.String(length=25), nullable=True),
    sa.Column('screen_depth', sa.String(length=10), nullable=True),
    sa.Column('continent', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('subdivision_1', sa.String(length=75), nullable=True),
    sa.Column('subdivision_2', sa.String(length=75), nullable=True),
    sa.Column('city', sa.String(length=75), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy_radius', sa.Integer(), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('_lang', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('events')
    op.drop_table('calendars')
    # ### end Alembic commands ###
