"""Update Visits and Events tables

Revision ID: b8b34950b93c
Revises: 0b39a6605996
Create Date: 2020-10-01 13:20:43.810289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b34950b93c'
down_revision = '0b39a6605996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('_lang', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('_referrer', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('accuracy_radius', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('browser', sa.String(length=25), nullable=True))
    op.add_column('events', sa.Column('city', sa.String(length=75), nullable=True))
    op.add_column('events', sa.Column('continent', sa.String(length=3), nullable=True))
    op.add_column('events', sa.Column('country', sa.String(length=3), nullable=True))
    op.add_column('events', sa.Column('doc_enc', sa.String(length=25), nullable=True))
    op.add_column('events', sa.Column('lang', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('platform', sa.String(length=25), nullable=True))
    op.add_column('events', sa.Column('referrer', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('screen_depth', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('screen_res', sa.String(length=25), nullable=True))
    op.add_column('events', sa.Column('subdivision_1', sa.String(length=75), nullable=True))
    op.add_column('events', sa.Column('subdivision_2', sa.String(length=75), nullable=True))
    op.add_column('events', sa.Column('time_zone', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('version', sa.String(length=25), nullable=True))
    op.drop_column('events', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('events', 'version')
    op.drop_column('events', 'time_zone')
    op.drop_column('events', 'subdivision_2')
    op.drop_column('events', 'subdivision_1')
    op.drop_column('events', 'screen_res')
    op.drop_column('events', 'screen_depth')
    op.drop_column('events', 'referrer')
    op.drop_column('events', 'platform')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'lang')
    op.drop_column('events', 'doc_enc')
    op.drop_column('events', 'country')
    op.drop_column('events', 'continent')
    op.drop_column('events', 'city')
    op.drop_column('events', 'browser')
    op.drop_column('events', 'accuracy_radius')
    op.drop_column('events', '_referrer')
    op.drop_column('events', '_lang')
    # ### end Alembic commands ###
