"""Update Events Table

Revision ID: ba95a9b673b1
Revises: 3ef119743b66
Create Date: 2020-10-09 23:11:12.929298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba95a9b673b1'
down_revision = '3ef119743b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('session', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'session')
    # ### end Alembic commands ###
