"""Adding new column at Events

Revision ID: f5fb42e02e69
Revises: 14034297ea86
Create Date: 2020-10-01 16:31:35.375524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fb42e02e69'
down_revision = '14034297ea86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('target', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'target')
    # ### end Alembic commands ###
